#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCD")]
	public partial class QLCDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietPhieuDat(ChiTietPhieuDat instance);
    partial void UpdateChiTietPhieuDat(ChiTietPhieuDat instance);
    partial void DeleteChiTietPhieuDat(ChiTietPhieuDat instance);
    partial void InsertTieuDe(TieuDe instance);
    partial void UpdateTieuDe(TieuDe instance);
    partial void DeleteTieuDe(TieuDe instance);
    partial void InsertChiTietPhieuThue(ChiTietPhieuThue instance);
    partial void UpdateChiTietPhieuThue(ChiTietPhieuThue instance);
    partial void DeleteChiTietPhieuThue(ChiTietPhieuThue instance);
    partial void InsertDanhMuc(DanhMuc instance);
    partial void UpdateDanhMuc(DanhMuc instance);
    partial void DeleteDanhMuc(DanhMuc instance);
    partial void InsertDia(Dia instance);
    partial void UpdateDia(Dia instance);
    partial void DeleteDia(Dia instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhieuDat(PhieuDat instance);
    partial void UpdatePhieuDat(PhieuDat instance);
    partial void DeletePhieuDat(PhieuDat instance);
    partial void InsertPhieuThue(PhieuThue instance);
    partial void UpdatePhieuThue(PhieuThue instance);
    partial void DeletePhieuThue(PhieuThue instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QLCDDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLCDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietPhieuDat> ChiTietPhieuDats
		{
			get
			{
				return this.GetTable<ChiTietPhieuDat>();
			}
		}
		
		public System.Data.Linq.Table<TieuDe> TieuDes
		{
			get
			{
				return this.GetTable<TieuDe>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuThue> ChiTietPhieuThues
		{
			get
			{
				return this.GetTable<ChiTietPhieuThue>();
			}
		}
		
		public System.Data.Linq.Table<DanhMuc> DanhMucs
		{
			get
			{
				return this.GetTable<DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<Dia> Dias
		{
			get
			{
				return this.GetTable<Dia>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhieuDat> PhieuDats
		{
			get
			{
				return this.GetTable<PhieuDat>();
			}
		}
		
		public System.Data.Linq.Table<PhieuThue> PhieuThues
		{
			get
			{
				return this.GetTable<PhieuThue>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuDat")]
	public partial class ChiTietPhieuDat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdChiTietPhieuDat;
		
		private string _IdTieuDe;
		
		private string _TenTieuDe;
		
		private System.Nullable<System.DateTime> _NgayXuLyDonDat;
		
		private System.Nullable<int> _IdPhieuDat;
		
		private EntityRef<TieuDe> _TieuDe;
		
		private EntityRef<PhieuDat> _PhieuDat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChiTietPhieuDatChanging(int value);
    partial void OnIdChiTietPhieuDatChanged();
    partial void OnIdTieuDeChanging(string value);
    partial void OnIdTieuDeChanged();
    partial void OnTenTieuDeChanging(string value);
    partial void OnTenTieuDeChanged();
    partial void OnNgayXuLyDonDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuLyDonDatChanged();
    partial void OnIdPhieuDatChanging(System.Nullable<int> value);
    partial void OnIdPhieuDatChanged();
    #endregion
		
		public ChiTietPhieuDat()
		{
			this._TieuDe = default(EntityRef<TieuDe>);
			this._PhieuDat = default(EntityRef<PhieuDat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChiTietPhieuDat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdChiTietPhieuDat
		{
			get
			{
				return this._IdChiTietPhieuDat;
			}
			set
			{
				if ((this._IdChiTietPhieuDat != value))
				{
					this.OnIdChiTietPhieuDatChanging(value);
					this.SendPropertyChanging();
					this._IdChiTietPhieuDat = value;
					this.SendPropertyChanged("IdChiTietPhieuDat");
					this.OnIdChiTietPhieuDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTieuDe", DbType="NVarChar(50)")]
		public string IdTieuDe
		{
			get
			{
				return this._IdTieuDe;
			}
			set
			{
				if ((this._IdTieuDe != value))
				{
					if (this._TieuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTieuDeChanging(value);
					this.SendPropertyChanging();
					this._IdTieuDe = value;
					this.SendPropertyChanged("IdTieuDe");
					this.OnIdTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTieuDe", DbType="NVarChar(50)")]
		public string TenTieuDe
		{
			get
			{
				return this._TenTieuDe;
			}
			set
			{
				if ((this._TenTieuDe != value))
				{
					this.OnTenTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TenTieuDe = value;
					this.SendPropertyChanged("TenTieuDe");
					this.OnTenTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuLyDonDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXuLyDonDat
		{
			get
			{
				return this._NgayXuLyDonDat;
			}
			set
			{
				if ((this._NgayXuLyDonDat != value))
				{
					this.OnNgayXuLyDonDatChanging(value);
					this.SendPropertyChanging();
					this._NgayXuLyDonDat = value;
					this.SendPropertyChanged("NgayXuLyDonDat");
					this.OnNgayXuLyDonDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieuDat", DbType="Int")]
		public System.Nullable<int> IdPhieuDat
		{
			get
			{
				return this._IdPhieuDat;
			}
			set
			{
				if ((this._IdPhieuDat != value))
				{
					if (this._PhieuDat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhieuDatChanging(value);
					this.SendPropertyChanging();
					this._IdPhieuDat = value;
					this.SendPropertyChanged("IdPhieuDat");
					this.OnIdPhieuDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_ChiTietPhieuDat", Storage="_TieuDe", ThisKey="IdTieuDe", OtherKey="IdTieuDe", IsForeignKey=true)]
		public TieuDe TieuDe
		{
			get
			{
				return this._TieuDe.Entity;
			}
			set
			{
				TieuDe previousValue = this._TieuDe.Entity;
				if (((previousValue != value) 
							|| (this._TieuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TieuDe.Entity = null;
						previousValue.ChiTietPhieuDats.Remove(this);
					}
					this._TieuDe.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuDats.Add(this);
						this._IdTieuDe = value.IdTieuDe;
					}
					else
					{
						this._IdTieuDe = default(string);
					}
					this.SendPropertyChanged("TieuDe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDat_ChiTietPhieuDat", Storage="_PhieuDat", ThisKey="IdPhieuDat", OtherKey="IdPhieuDat", IsForeignKey=true)]
		public PhieuDat PhieuDat
		{
			get
			{
				return this._PhieuDat.Entity;
			}
			set
			{
				PhieuDat previousValue = this._PhieuDat.Entity;
				if (((previousValue != value) 
							|| (this._PhieuDat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuDat.Entity = null;
						previousValue.ChiTietPhieuDats.Remove(this);
					}
					this._PhieuDat.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuDats.Add(this);
						this._IdPhieuDat = value.IdPhieuDat;
					}
					else
					{
						this._IdPhieuDat = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhieuDat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TieuDe")]
	public partial class TieuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdTieuDe;
		
		private string _TenTieuDe;
		
		private System.Nullable<int> _SoLuongDia;
		
		private System.Nullable<int> _SoLuongDiaCoSan;
		
		private System.Nullable<bool> _TrangThaiXoa;
		
		private System.Nullable<int> _IdDanhMuc;
		
		private EntitySet<ChiTietPhieuDat> _ChiTietPhieuDats;
		
		private EntitySet<Dia> _Dias;
		
		private EntityRef<DanhMuc> _DanhMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTieuDeChanging(string value);
    partial void OnIdTieuDeChanged();
    partial void OnTenTieuDeChanging(string value);
    partial void OnTenTieuDeChanged();
    partial void OnSoLuongDiaChanging(System.Nullable<int> value);
    partial void OnSoLuongDiaChanged();
    partial void OnSoLuongDiaCoSanChanging(System.Nullable<int> value);
    partial void OnSoLuongDiaCoSanChanged();
    partial void OnTrangThaiXoaChanging(System.Nullable<bool> value);
    partial void OnTrangThaiXoaChanged();
    partial void OnIdDanhMucChanging(System.Nullable<int> value);
    partial void OnIdDanhMucChanged();
    #endregion
		
		public TieuDe()
		{
			this._ChiTietPhieuDats = new EntitySet<ChiTietPhieuDat>(new Action<ChiTietPhieuDat>(this.attach_ChiTietPhieuDats), new Action<ChiTietPhieuDat>(this.detach_ChiTietPhieuDats));
			this._Dias = new EntitySet<Dia>(new Action<Dia>(this.attach_Dias), new Action<Dia>(this.detach_Dias));
			this._DanhMuc = default(EntityRef<DanhMuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTieuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdTieuDe
		{
			get
			{
				return this._IdTieuDe;
			}
			set
			{
				if ((this._IdTieuDe != value))
				{
					this.OnIdTieuDeChanging(value);
					this.SendPropertyChanging();
					this._IdTieuDe = value;
					this.SendPropertyChanged("IdTieuDe");
					this.OnIdTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTieuDe", DbType="NVarChar(50)")]
		public string TenTieuDe
		{
			get
			{
				return this._TenTieuDe;
			}
			set
			{
				if ((this._TenTieuDe != value))
				{
					this.OnTenTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TenTieuDe = value;
					this.SendPropertyChanged("TenTieuDe");
					this.OnTenTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDia", DbType="Int")]
		public System.Nullable<int> SoLuongDia
		{
			get
			{
				return this._SoLuongDia;
			}
			set
			{
				if ((this._SoLuongDia != value))
				{
					this.OnSoLuongDiaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDia = value;
					this.SendPropertyChanged("SoLuongDia");
					this.OnSoLuongDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDiaCoSan", DbType="Int")]
		public System.Nullable<int> SoLuongDiaCoSan
		{
			get
			{
				return this._SoLuongDiaCoSan;
			}
			set
			{
				if ((this._SoLuongDiaCoSan != value))
				{
					this.OnSoLuongDiaCoSanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDiaCoSan = value;
					this.SendPropertyChanged("SoLuongDiaCoSan");
					this.OnSoLuongDiaCoSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiXoa", DbType="Bit")]
		public System.Nullable<bool> TrangThaiXoa
		{
			get
			{
				return this._TrangThaiXoa;
			}
			set
			{
				if ((this._TrangThaiXoa != value))
				{
					this.OnTrangThaiXoaChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiXoa = value;
					this.SendPropertyChanged("TrangThaiXoa");
					this.OnTrangThaiXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMuc", DbType="Int")]
		public System.Nullable<int> IdDanhMuc
		{
			get
			{
				return this._IdDanhMuc;
			}
			set
			{
				if ((this._IdDanhMuc != value))
				{
					if (this._DanhMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDanhMucChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMuc = value;
					this.SendPropertyChanged("IdDanhMuc");
					this.OnIdDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_ChiTietPhieuDat", Storage="_ChiTietPhieuDats", ThisKey="IdTieuDe", OtherKey="IdTieuDe")]
		public EntitySet<ChiTietPhieuDat> ChiTietPhieuDats
		{
			get
			{
				return this._ChiTietPhieuDats;
			}
			set
			{
				this._ChiTietPhieuDats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_Dia", Storage="_Dias", ThisKey="IdTieuDe", OtherKey="IdTieuDe")]
		public EntitySet<Dia> Dias
		{
			get
			{
				return this._Dias;
			}
			set
			{
				this._Dias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_TieuDe", Storage="_DanhMuc", ThisKey="IdDanhMuc", OtherKey="IdDanhMuc", IsForeignKey=true)]
		public DanhMuc DanhMuc
		{
			get
			{
				return this._DanhMuc.Entity;
			}
			set
			{
				DanhMuc previousValue = this._DanhMuc.Entity;
				if (((previousValue != value) 
							|| (this._DanhMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhMuc.Entity = null;
						previousValue.TieuDes.Remove(this);
					}
					this._DanhMuc.Entity = value;
					if ((value != null))
					{
						value.TieuDes.Add(this);
						this._IdDanhMuc = value.IdDanhMuc;
					}
					else
					{
						this._IdDanhMuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("DanhMuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuDats(ChiTietPhieuDat entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = this;
		}
		
		private void detach_ChiTietPhieuDats(ChiTietPhieuDat entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = null;
		}
		
		private void attach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = this;
		}
		
		private void detach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuThue")]
	public partial class ChiTietPhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdChiTietPhieuThue;
		
		private string _IdDia;
		
		private System.Nullable<System.DateTime> _NgayTraDiaDuKien;
		
		private System.Nullable<decimal> _PhiThue;
		
		private System.Nullable<System.DateTime> _NgayTraDiaThucTe;
		
		private System.Nullable<decimal> _PhiTre;
		
		private System.Nullable<bool> _TrangThaiNoPhiTre;
		
		private System.Nullable<bool> _TrangThaiTraPhiTre;
		
		private System.Nullable<int> _IdPhieuThue;
		
		private EntityRef<Dia> _Dia;
		
		private EntityRef<PhieuThue> _PhieuThue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChiTietPhieuThueChanging(int value);
    partial void OnIdChiTietPhieuThueChanged();
    partial void OnIdDiaChanging(string value);
    partial void OnIdDiaChanged();
    partial void OnNgayTraDiaDuKienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraDiaDuKienChanged();
    partial void OnPhiThueChanging(System.Nullable<decimal> value);
    partial void OnPhiThueChanged();
    partial void OnNgayTraDiaThucTeChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraDiaThucTeChanged();
    partial void OnPhiTreChanging(System.Nullable<decimal> value);
    partial void OnPhiTreChanged();
    partial void OnTrangThaiNoPhiTreChanging(System.Nullable<bool> value);
    partial void OnTrangThaiNoPhiTreChanged();
    partial void OnTrangThaiTraPhiTreChanging(System.Nullable<bool> value);
    partial void OnTrangThaiTraPhiTreChanged();
    partial void OnIdPhieuThueChanging(System.Nullable<int> value);
    partial void OnIdPhieuThueChanged();
    #endregion
		
		public ChiTietPhieuThue()
		{
			this._Dia = default(EntityRef<Dia>);
			this._PhieuThue = default(EntityRef<PhieuThue>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChiTietPhieuThue", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdChiTietPhieuThue
		{
			get
			{
				return this._IdChiTietPhieuThue;
			}
			set
			{
				if ((this._IdChiTietPhieuThue != value))
				{
					this.OnIdChiTietPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._IdChiTietPhieuThue = value;
					this.SendPropertyChanged("IdChiTietPhieuThue");
					this.OnIdChiTietPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDia", DbType="NVarChar(50)")]
		public string IdDia
		{
			get
			{
				return this._IdDia;
			}
			set
			{
				if ((this._IdDia != value))
				{
					if (this._Dia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDiaChanging(value);
					this.SendPropertyChanging();
					this._IdDia = value;
					this.SendPropertyChanged("IdDia");
					this.OnIdDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraDiaDuKien", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTraDiaDuKien
		{
			get
			{
				return this._NgayTraDiaDuKien;
			}
			set
			{
				if ((this._NgayTraDiaDuKien != value))
				{
					this.OnNgayTraDiaDuKienChanging(value);
					this.SendPropertyChanging();
					this._NgayTraDiaDuKien = value;
					this.SendPropertyChanged("NgayTraDiaDuKien");
					this.OnNgayTraDiaDuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiThue", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PhiThue
		{
			get
			{
				return this._PhiThue;
			}
			set
			{
				if ((this._PhiThue != value))
				{
					this.OnPhiThueChanging(value);
					this.SendPropertyChanging();
					this._PhiThue = value;
					this.SendPropertyChanged("PhiThue");
					this.OnPhiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraDiaThucTe", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTraDiaThucTe
		{
			get
			{
				return this._NgayTraDiaThucTe;
			}
			set
			{
				if ((this._NgayTraDiaThucTe != value))
				{
					this.OnNgayTraDiaThucTeChanging(value);
					this.SendPropertyChanging();
					this._NgayTraDiaThucTe = value;
					this.SendPropertyChanged("NgayTraDiaThucTe");
					this.OnNgayTraDiaThucTeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiTre", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PhiTre
		{
			get
			{
				return this._PhiTre;
			}
			set
			{
				if ((this._PhiTre != value))
				{
					this.OnPhiTreChanging(value);
					this.SendPropertyChanging();
					this._PhiTre = value;
					this.SendPropertyChanged("PhiTre");
					this.OnPhiTreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiNoPhiTre", DbType="Bit")]
		public System.Nullable<bool> TrangThaiNoPhiTre
		{
			get
			{
				return this._TrangThaiNoPhiTre;
			}
			set
			{
				if ((this._TrangThaiNoPhiTre != value))
				{
					this.OnTrangThaiNoPhiTreChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiNoPhiTre = value;
					this.SendPropertyChanged("TrangThaiNoPhiTre");
					this.OnTrangThaiNoPhiTreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiTraPhiTre", DbType="Bit")]
		public System.Nullable<bool> TrangThaiTraPhiTre
		{
			get
			{
				return this._TrangThaiTraPhiTre;
			}
			set
			{
				if ((this._TrangThaiTraPhiTre != value))
				{
					this.OnTrangThaiTraPhiTreChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiTraPhiTre = value;
					this.SendPropertyChanged("TrangThaiTraPhiTre");
					this.OnTrangThaiTraPhiTreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieuThue", DbType="Int")]
		public System.Nullable<int> IdPhieuThue
		{
			get
			{
				return this._IdPhieuThue;
			}
			set
			{
				if ((this._IdPhieuThue != value))
				{
					if (this._PhieuThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._IdPhieuThue = value;
					this.SendPropertyChanged("IdPhieuThue");
					this.OnIdPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dia_ChiTietPhieuThue", Storage="_Dia", ThisKey="IdDia", OtherKey="IdDia", IsForeignKey=true)]
		public Dia Dia
		{
			get
			{
				return this._Dia.Entity;
			}
			set
			{
				Dia previousValue = this._Dia.Entity;
				if (((previousValue != value) 
							|| (this._Dia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dia.Entity = null;
						previousValue.ChiTietPhieuThues.Remove(this);
					}
					this._Dia.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuThues.Add(this);
						this._IdDia = value.IdDia;
					}
					else
					{
						this._IdDia = default(string);
					}
					this.SendPropertyChanged("Dia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuThue_ChiTietPhieuThue", Storage="_PhieuThue", ThisKey="IdPhieuThue", OtherKey="IdPhieuThue", IsForeignKey=true)]
		public PhieuThue PhieuThue
		{
			get
			{
				return this._PhieuThue.Entity;
			}
			set
			{
				PhieuThue previousValue = this._PhieuThue.Entity;
				if (((previousValue != value) 
							|| (this._PhieuThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuThue.Entity = null;
						previousValue.ChiTietPhieuThues.Remove(this);
					}
					this._PhieuThue.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuThues.Add(this);
						this._IdPhieuThue = value.IdPhieuThue;
					}
					else
					{
						this._IdPhieuThue = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhieuThue");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMuc")]
	public partial class DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDanhMuc;
		
		private string _TenDanhMuc;
		
		private System.Nullable<bool> _TrangThaiXoa;
		
		private System.Nullable<decimal> _PhiThue;
		
		private System.Nullable<decimal> _PhiTreHan;
		
		private System.Nullable<int> _SoNgayThue;
		
		private EntitySet<TieuDe> _TieuDes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDanhMucChanging(int value);
    partial void OnIdDanhMucChanged();
    partial void OnTenDanhMucChanging(string value);
    partial void OnTenDanhMucChanged();
    partial void OnTrangThaiXoaChanging(System.Nullable<bool> value);
    partial void OnTrangThaiXoaChanged();
    partial void OnPhiThueChanging(System.Nullable<decimal> value);
    partial void OnPhiThueChanged();
    partial void OnPhiTreHanChanging(System.Nullable<decimal> value);
    partial void OnPhiTreHanChanged();
    partial void OnSoNgayThueChanging(System.Nullable<int> value);
    partial void OnSoNgayThueChanged();
    #endregion
		
		public DanhMuc()
		{
			this._TieuDes = new EntitySet<TieuDe>(new Action<TieuDe>(this.attach_TieuDes), new Action<TieuDe>(this.detach_TieuDes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDanhMuc
		{
			get
			{
				return this._IdDanhMuc;
			}
			set
			{
				if ((this._IdDanhMuc != value))
				{
					this.OnIdDanhMucChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMuc = value;
					this.SendPropertyChanged("IdDanhMuc");
					this.OnIdDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMuc", DbType="NVarChar(50)")]
		public string TenDanhMuc
		{
			get
			{
				return this._TenDanhMuc;
			}
			set
			{
				if ((this._TenDanhMuc != value))
				{
					this.OnTenDanhMucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMuc = value;
					this.SendPropertyChanged("TenDanhMuc");
					this.OnTenDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiXoa", DbType="Bit")]
		public System.Nullable<bool> TrangThaiXoa
		{
			get
			{
				return this._TrangThaiXoa;
			}
			set
			{
				if ((this._TrangThaiXoa != value))
				{
					this.OnTrangThaiXoaChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiXoa = value;
					this.SendPropertyChanged("TrangThaiXoa");
					this.OnTrangThaiXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiThue", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PhiThue
		{
			get
			{
				return this._PhiThue;
			}
			set
			{
				if ((this._PhiThue != value))
				{
					this.OnPhiThueChanging(value);
					this.SendPropertyChanging();
					this._PhiThue = value;
					this.SendPropertyChanged("PhiThue");
					this.OnPhiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiTreHan", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PhiTreHan
		{
			get
			{
				return this._PhiTreHan;
			}
			set
			{
				if ((this._PhiTreHan != value))
				{
					this.OnPhiTreHanChanging(value);
					this.SendPropertyChanging();
					this._PhiTreHan = value;
					this.SendPropertyChanged("PhiTreHan");
					this.OnPhiTreHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayThue", DbType="Int")]
		public System.Nullable<int> SoNgayThue
		{
			get
			{
				return this._SoNgayThue;
			}
			set
			{
				if ((this._SoNgayThue != value))
				{
					this.OnSoNgayThueChanging(value);
					this.SendPropertyChanging();
					this._SoNgayThue = value;
					this.SendPropertyChanged("SoNgayThue");
					this.OnSoNgayThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_TieuDe", Storage="_TieuDes", ThisKey="IdDanhMuc", OtherKey="IdDanhMuc")]
		public EntitySet<TieuDe> TieuDes
		{
			get
			{
				return this._TieuDes;
			}
			set
			{
				this._TieuDes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TieuDes(TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.DanhMuc = this;
		}
		
		private void detach_TieuDes(TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.DanhMuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dia")]
	public partial class Dia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdDia;
		
		private string _TrangThaiThue;
		
		private System.Nullable<bool> _TrangThaiXoa;
		
		private string _IdTieuDe;
		
		private EntitySet<ChiTietPhieuThue> _ChiTietPhieuThues;
		
		private EntityRef<TieuDe> _TieuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDiaChanging(string value);
    partial void OnIdDiaChanged();
    partial void OnTrangThaiThueChanging(string value);
    partial void OnTrangThaiThueChanged();
    partial void OnTrangThaiXoaChanging(System.Nullable<bool> value);
    partial void OnTrangThaiXoaChanged();
    partial void OnIdTieuDeChanging(string value);
    partial void OnIdTieuDeChanged();
    #endregion
		
		public Dia()
		{
			this._ChiTietPhieuThues = new EntitySet<ChiTietPhieuThue>(new Action<ChiTietPhieuThue>(this.attach_ChiTietPhieuThues), new Action<ChiTietPhieuThue>(this.detach_ChiTietPhieuThues));
			this._TieuDe = default(EntityRef<TieuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdDia
		{
			get
			{
				return this._IdDia;
			}
			set
			{
				if ((this._IdDia != value))
				{
					this.OnIdDiaChanging(value);
					this.SendPropertyChanging();
					this._IdDia = value;
					this.SendPropertyChanged("IdDia");
					this.OnIdDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiThue", DbType="NVarChar(50)")]
		public string TrangThaiThue
		{
			get
			{
				return this._TrangThaiThue;
			}
			set
			{
				if ((this._TrangThaiThue != value))
				{
					this.OnTrangThaiThueChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiThue = value;
					this.SendPropertyChanged("TrangThaiThue");
					this.OnTrangThaiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiXoa", DbType="Bit")]
		public System.Nullable<bool> TrangThaiXoa
		{
			get
			{
				return this._TrangThaiXoa;
			}
			set
			{
				if ((this._TrangThaiXoa != value))
				{
					this.OnTrangThaiXoaChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiXoa = value;
					this.SendPropertyChanged("TrangThaiXoa");
					this.OnTrangThaiXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTieuDe", DbType="NVarChar(50)")]
		public string IdTieuDe
		{
			get
			{
				return this._IdTieuDe;
			}
			set
			{
				if ((this._IdTieuDe != value))
				{
					if (this._TieuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTieuDeChanging(value);
					this.SendPropertyChanging();
					this._IdTieuDe = value;
					this.SendPropertyChanged("IdTieuDe");
					this.OnIdTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dia_ChiTietPhieuThue", Storage="_ChiTietPhieuThues", ThisKey="IdDia", OtherKey="IdDia")]
		public EntitySet<ChiTietPhieuThue> ChiTietPhieuThues
		{
			get
			{
				return this._ChiTietPhieuThues;
			}
			set
			{
				this._ChiTietPhieuThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_Dia", Storage="_TieuDe", ThisKey="IdTieuDe", OtherKey="IdTieuDe", IsForeignKey=true)]
		public TieuDe TieuDe
		{
			get
			{
				return this._TieuDe.Entity;
			}
			set
			{
				TieuDe previousValue = this._TieuDe.Entity;
				if (((previousValue != value) 
							|| (this._TieuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TieuDe.Entity = null;
						previousValue.Dias.Remove(this);
					}
					this._TieuDe.Entity = value;
					if ((value != null))
					{
						value.Dias.Add(this);
						this._IdTieuDe = value.IdTieuDe;
					}
					else
					{
						this._IdTieuDe = default(string);
					}
					this.SendPropertyChanged("TieuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuThues(ChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.Dia = this;
		}
		
		private void detach_ChiTietPhieuThues(ChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.Dia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdKhachHang;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private System.Nullable<bool> _TrangThaiXoa;
		
		private EntitySet<PhieuDat> _PhieuDats;
		
		private EntitySet<PhieuThue> _PhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKhachHangChanging(string value);
    partial void OnIdKhachHangChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnTrangThaiXoaChanging(System.Nullable<bool> value);
    partial void OnTrangThaiXoaChanged();
    #endregion
		
		public KhachHang()
		{
			this._PhieuDats = new EntitySet<PhieuDat>(new Action<PhieuDat>(this.attach_PhieuDats), new Action<PhieuDat>(this.detach_PhieuDats));
			this._PhieuThues = new EntitySet<PhieuThue>(new Action<PhieuThue>(this.attach_PhieuThues), new Action<PhieuThue>(this.detach_PhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdKhachHang
		{
			get
			{
				return this._IdKhachHang;
			}
			set
			{
				if ((this._IdKhachHang != value))
				{
					this.OnIdKhachHangChanging(value);
					this.SendPropertyChanging();
					this._IdKhachHang = value;
					this.SendPropertyChanged("IdKhachHang");
					this.OnIdKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiXoa", DbType="Bit")]
		public System.Nullable<bool> TrangThaiXoa
		{
			get
			{
				return this._TrangThaiXoa;
			}
			set
			{
				if ((this._TrangThaiXoa != value))
				{
					this.OnTrangThaiXoaChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiXoa = value;
					this.SendPropertyChanged("TrangThaiXoa");
					this.OnTrangThaiXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDat", Storage="_PhieuDats", ThisKey="IdKhachHang", OtherKey="IdKhachHang")]
		public EntitySet<PhieuDat> PhieuDats
		{
			get
			{
				return this._PhieuDats;
			}
			set
			{
				this._PhieuDats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuThue", Storage="_PhieuThues", ThisKey="IdKhachHang", OtherKey="IdKhachHang")]
		public EntitySet<PhieuThue> PhieuThues
		{
			get
			{
				return this._PhieuThues;
			}
			set
			{
				this._PhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDats(PhieuDat entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_PhieuDats(PhieuDat entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_PhieuThues(PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_PhieuThues(PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdNhanVien;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNhanVienChanging(string value);
    partial void OnIdNhanVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    #endregion
		
		public NhanVien()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdNhanVien
		{
			get
			{
				return this._IdNhanVien;
			}
			set
			{
				if ((this._IdNhanVien != value))
				{
					this.OnIdNhanVienChanging(value);
					this.SendPropertyChanging();
					this._IdNhanVien = value;
					this.SendPropertyChanged("IdNhanVien");
					this.OnIdNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="IdNhanVien", OtherKey="IdNhanVien")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuDat")]
	public partial class PhieuDat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPhieuDat;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _IdKhachHang;
		
		private EntitySet<ChiTietPhieuDat> _ChiTietPhieuDats;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPhieuDatChanging(int value);
    partial void OnIdPhieuDatChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnIdKhachHangChanging(string value);
    partial void OnIdKhachHangChanged();
    #endregion
		
		public PhieuDat()
		{
			this._ChiTietPhieuDats = new EntitySet<ChiTietPhieuDat>(new Action<ChiTietPhieuDat>(this.attach_ChiTietPhieuDats), new Action<ChiTietPhieuDat>(this.detach_ChiTietPhieuDats));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieuDat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPhieuDat
		{
			get
			{
				return this._IdPhieuDat;
			}
			set
			{
				if ((this._IdPhieuDat != value))
				{
					this.OnIdPhieuDatChanging(value);
					this.SendPropertyChanging();
					this._IdPhieuDat = value;
					this.SendPropertyChanged("IdPhieuDat");
					this.OnIdPhieuDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhachHang", DbType="NVarChar(50)")]
		public string IdKhachHang
		{
			get
			{
				return this._IdKhachHang;
			}
			set
			{
				if ((this._IdKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKhachHangChanging(value);
					this.SendPropertyChanging();
					this._IdKhachHang = value;
					this.SendPropertyChanged("IdKhachHang");
					this.OnIdKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDat_ChiTietPhieuDat", Storage="_ChiTietPhieuDats", ThisKey="IdPhieuDat", OtherKey="IdPhieuDat")]
		public EntitySet<ChiTietPhieuDat> ChiTietPhieuDats
		{
			get
			{
				return this._ChiTietPhieuDats;
			}
			set
			{
				this._ChiTietPhieuDats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDat", Storage="_KhachHang", ThisKey="IdKhachHang", OtherKey="IdKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.PhieuDats.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.PhieuDats.Add(this);
						this._IdKhachHang = value.IdKhachHang;
					}
					else
					{
						this._IdKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuDats(ChiTietPhieuDat entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDat = this;
		}
		
		private void detach_ChiTietPhieuDats(ChiTietPhieuDat entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuThue")]
	public partial class PhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPhieuThue;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<decimal> _TongPhiThue;
		
		private string _IdKhachHang;
		
		private EntitySet<ChiTietPhieuThue> _ChiTietPhieuThues;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPhieuThueChanging(int value);
    partial void OnIdPhieuThueChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnTongPhiThueChanging(System.Nullable<decimal> value);
    partial void OnTongPhiThueChanged();
    partial void OnIdKhachHangChanging(string value);
    partial void OnIdKhachHangChanged();
    #endregion
		
		public PhieuThue()
		{
			this._ChiTietPhieuThues = new EntitySet<ChiTietPhieuThue>(new Action<ChiTietPhieuThue>(this.attach_ChiTietPhieuThues), new Action<ChiTietPhieuThue>(this.detach_ChiTietPhieuThues));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieuThue", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPhieuThue
		{
			get
			{
				return this._IdPhieuThue;
			}
			set
			{
				if ((this._IdPhieuThue != value))
				{
					this.OnIdPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._IdPhieuThue = value;
					this.SendPropertyChanged("IdPhieuThue");
					this.OnIdPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongPhiThue", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TongPhiThue
		{
			get
			{
				return this._TongPhiThue;
			}
			set
			{
				if ((this._TongPhiThue != value))
				{
					this.OnTongPhiThueChanging(value);
					this.SendPropertyChanging();
					this._TongPhiThue = value;
					this.SendPropertyChanged("TongPhiThue");
					this.OnTongPhiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhachHang", DbType="NVarChar(50)")]
		public string IdKhachHang
		{
			get
			{
				return this._IdKhachHang;
			}
			set
			{
				if ((this._IdKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKhachHangChanging(value);
					this.SendPropertyChanging();
					this._IdKhachHang = value;
					this.SendPropertyChanged("IdKhachHang");
					this.OnIdKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuThue_ChiTietPhieuThue", Storage="_ChiTietPhieuThues", ThisKey="IdPhieuThue", OtherKey="IdPhieuThue")]
		public EntitySet<ChiTietPhieuThue> ChiTietPhieuThues
		{
			get
			{
				return this._ChiTietPhieuThues;
			}
			set
			{
				this._ChiTietPhieuThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuThue", Storage="_KhachHang", ThisKey="IdKhachHang", OtherKey="IdKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.PhieuThues.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.PhieuThues.Add(this);
						this._IdKhachHang = value.IdKhachHang;
					}
					else
					{
						this._IdKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuThues(ChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.PhieuThue = this;
		}
		
		private void detach_ChiTietPhieuThues(ChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.PhieuThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTaiKhoan;
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private string _IdNhanVien;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTaiKhoanChanging(int value);
    partial void OnIdTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnIdNhanVienChanging(string value);
    partial void OnIdNhanVienChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTaiKhoan
		{
			get
			{
				return this._IdTaiKhoan;
			}
			set
			{
				if ((this._IdTaiKhoan != value))
				{
					this.OnIdTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IdTaiKhoan = value;
					this.SendPropertyChanged("IdTaiKhoan");
					this.OnIdTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(50)")]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNhanVien", DbType="NVarChar(50)")]
		public string IdNhanVien
		{
			get
			{
				return this._IdNhanVien;
			}
			set
			{
				if ((this._IdNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNhanVienChanging(value);
					this.SendPropertyChanging();
					this._IdNhanVien = value;
					this.SendPropertyChanged("IdNhanVien");
					this.OnIdNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="IdNhanVien", OtherKey="IdNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._IdNhanVien = value.IdNhanVien;
					}
					else
					{
						this._IdNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
